#!/usr/bin/env bash

join_by() {
  local __out_var="$1"
  local separator="$2"
  shift 2

  # %b интерпретирует escape-последовательности в аргументах
  local sep
  printf -v sep '%b' "$separator"

  local out=""
  local first=1
  local arg
  for arg in "$@"; do
    if (( first )); then
      out+="$arg"
      first=0
    else
      out+="${sep}${arg}"
    fi
  done

  printf -v "$__out_var" '%s' "$out"
}

render_template() {
    eval "cat <<EOF
$(<$1)
EOF
" 2> /dev/null > $2
}

echo "==========================================================="
echo " Radio streaming with Docker"
echo " https://github.com/uamana/"
echo ""
echo " This software distributed under the MIT license"
echo " Copyright (c) 2026 - ADMFM <sergey@admfm.net>"
echo "==========================================================="

if [ -f config.sh ]; then
    source config.sh
else
    echo "config.sh not found"
    exit 1
fi

sources_array=()
for stream in "${STREAMS[@]}"; do
    harbor_var="HARBOR_${stream}"
    harbor_val="${!harbor_var}"

    icecast_var="ICECAST_${stream}"
    icecast_val="${!icecast_var}"

    if [ -n "$harbor_val" ]; then
        IFS=':' read -r harbor_mount harbor_port harbor_pass <<< "$harbor_val"
        sources_array+=( "(\"$stream\", mksafe(input.harbor(\"$harbor_mount\", port=$harbor_port, password=\"$harbor_pass\", icy=true)))" )
    elif [ -n "$icecast_val" ]; then
        sources_array+=( "(\"$stream\", mksafe(input.http(\"$icecast_val\")))" )
    fi
done

join_by SOURCES ",\n" "${sources_array[@]}"

echo "Generating Nginx configuration..."
render_template $TEMPLATE_NGINX nginx/nginx.conf

echo "Generating Liquidsoap settings..."
render_template $TEMPLATE_LQ_SETTINGS scripts/settings.liq

echo "Generating Icecast configuration..."
render_template $TEMPLATE_ICECAST icecast/icecast.xml

echo "Generating .env for docker-compose.yml..."
cat <<EOF > .env
# This file is auto-generated by gen_config.sh
# Do not edit this file manually
# Date: $(date)
CONTAINER_TMPFS_SIZE=${CONTAINER_TMPFS_SIZE:-16m}
CERTBOT_RENEW_INTERVAL=${CERTBOT_RENEW_INTERVAL:-1d}
ICECAST_CERT_CHECK_INTERVAL=${ICECAST_CERT_CHECK_INTERVAL:-12h}
NGINX_CERT_CHECK_INTERVAL=${NGINX_CERT_CHECK_INTERVAL:-12h}
EOF