#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  ./self_signed.sh [--domain example.com] [--days 365] [--force]

Generates a self-signed TLS certificate in:
  ./certbot/conf/live/<DOMAIN>/{fullchain.pem,privkey.pem}

This matches nginx config paths:
  /etc/letsencrypt/live/<DOMAIN>/fullchain.pem
  /etc/letsencrypt/live/<DOMAIN>/privkey.pem
EOF
}

DOMAIN_ARG=""
DAYS="365"
FORCE="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)
      DOMAIN_ARG="${2:-}"
      shift 2
      ;;
    --days)
      DAYS="${2:-}"
      shift 2
      ;;
    --force)
      FORCE="1"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ -f "${ROOT_DIR}/config.sh" ]]; then
  source "${ROOT_DIR}/config.sh"
fi

DOMAIN="${DOMAIN_ARG:-${DOMAIN:-}}"
if [[ -z "${DOMAIN}" ]]; then
  echo "DOMAIN is not set. Set it in config.sh or pass --domain." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl not found; please install it to generate self-signed certs." >&2
  exit 1
fi

CERTBOT_CONF_DIR="${ROOT_DIR}/certbot/conf"
LIVE_DIR="${CERTBOT_CONF_DIR}/live/${DOMAIN}"
ARCHIVE_DIR="${CERTBOT_CONF_DIR}/archive/${DOMAIN}"
RENEWAL_DIR="${CERTBOT_CONF_DIR}/renewal"

mkdir -p "${LIVE_DIR}" "${ARCHIVE_DIR}" "${RENEWAL_DIR}"

if [[ -e "${LIVE_DIR}/privkey.pem" || -e "${LIVE_DIR}/fullchain.pem" ]] && [[ "${FORCE}" != "1" ]]; then
  echo "Refusing to overwrite existing certs in ${LIVE_DIR}. Re-run with --force to overwrite." >&2
  exit 1
fi

tmp_dir="$(mktemp -d)"
cleanup() { rm -rf "${tmp_dir}"; }
trap cleanup EXIT

key_tmp="${tmp_dir}/privkey.pem"
cert_tmp="${tmp_dir}/cert.pem"

if openssl req -help 2>&1 | grep -q -- '-addext'; then
  openssl req -x509 -nodes \
    -newkey "rsa:2048" \
    -days "${DAYS}" \
    -keyout "${key_tmp}" \
    -out "${cert_tmp}" \
    -subj "/CN=${DOMAIN}" \
    -addext "subjectAltName=DNS:${DOMAIN}"
else
  openssl_cnf="${tmp_dir}/openssl.cnf"
  cat > "${openssl_cnf}" <<EOF
[ req ]
default_bits       = 2048
prompt             = no
default_md         = sha256
distinguished_name = dn
x509_extensions    = v3_req

[ dn ]
CN = ${DOMAIN}

[ v3_req ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = ${DOMAIN}
EOF
  openssl req -x509 -nodes \
    -newkey "rsa:2048" \
    -days "${DAYS}" \
    -keyout "${key_tmp}" \
    -out "${cert_tmp}" \
    -config "${openssl_cnf}"
fi

chmod 600 "${key_tmp}"

# Create a certbot-like layout (archive + live symlinks)
cert_ver="1"

install -m 600 "${key_tmp}" "${ARCHIVE_DIR}/privkey${cert_ver}.pem"
install -m 644 "${cert_tmp}" "${ARCHIVE_DIR}/cert${cert_ver}.pem"
install -m 644 "${cert_tmp}" "${ARCHIVE_DIR}/chain${cert_ver}.pem"
install -m 644 "${cert_tmp}" "${ARCHIVE_DIR}/fullchain${cert_ver}.pem"

rm -f \
  "${LIVE_DIR}/privkey.pem" \
  "${LIVE_DIR}/cert.pem" \
  "${LIVE_DIR}/chain.pem" \
  "${LIVE_DIR}/fullchain.pem"

ln -sf "../../archive/${DOMAIN}/privkey${cert_ver}.pem" "${LIVE_DIR}/privkey.pem"
ln -sf "../../archive/${DOMAIN}/cert${cert_ver}.pem" "${LIVE_DIR}/cert.pem"
ln -sf "../../archive/${DOMAIN}/chain${cert_ver}.pem" "${LIVE_DIR}/chain.pem"
ln -sf "../../archive/${DOMAIN}/fullchain${cert_ver}.pem" "${LIVE_DIR}/fullchain.pem"

# Optional: create a minimal renewal file (not used for self-signed, but keeps layout familiar)
cat > "${RENEWAL_DIR}/${DOMAIN}.conf" <<EOF
# Self-signed certificate generated by self_signed.sh
# Replace with a real Let's Encrypt cert when ready.
[renewalparams]
authenticator = standalone
account = self-signed
server = self-signed
EOF

echo "Generated self-signed cert for ${DOMAIN}"
echo " - ${LIVE_DIR}/fullchain.pem"
echo " - ${LIVE_DIR}/privkey.pem"
